AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'
